version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    ports:
    - 8000:8080
    links:
    - postgres

  postgres:
    build:
      context: ./
      dockerfile: pg.Dockerfile
    ports:
    - 5432:5432